package:
  name: paqman
  version: "1.0.0"  # Change this to your desired version

source:
  git_url: https://github.com/samtobam/paqman.git
  git_rev: main

build:
  number: 0 # Increment with each new build
  scripts:
    - python=3.8.*
    - bin/paqman
    - bash post-link.sh

requirements:
  run:
  - bioconda::busco=6.0.0
  - bioconda::merqury=1.3
  - bioconda::quast=5.3.0
  - bioconda::filtlong=0.2.1
  - bioconda::seqtk=1.5
  - bioconda::craq=1.0.9
  - bioconda::seqkit=2.10.0
  - conda-forge::r-ggplot2=3.5.2
  - conda-forge::r-ggpubr=0.6.1
  - conda-forge::r-ggsci=3.2.0
  - conda-forge::r-svglite=2.1.3
  - conda-forge::r-ggsci=3.2.0
  - conda-forge::r-reshape2=1.4.4
  - conda-forge::r-devtools=2.4.5
  - conda-forge::r-stringr=1.5.1
  - pwwang::ggradar=0.2.0

test:
  commands:
    - "paqman.sh --help"

about:
  home: "https://github.com/samtobam/paqman"
  summary: "Post-Assembly quality manager"
